# Generated by Django 5.1.2 on 2024-11-21 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_delete_productattributevalue"),
        ("products", "0005_productattributevalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattributevalue",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="products.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productattributevalue",
            unique_together={("product", "attribute")},
        ),
    ]
