# Generated by Django 5.1.2 on 2024-12-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
