# Generated by Django 5.1.2 on 2024-12-05 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
